name: CMake Build

on:
  push:
    branches:
      - v2.0

  pull_request:
    branches:
      - v2.0

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.24
      with:
        cuda: '12.6'


    - name: Check CUDA
      run: nvcc --version


    - name: Configure CMake
      run: cmake -B build -S .


    - name: Build
      run: cmake --build build
